AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Nepali Translator Lambda'
Parameters:
  LambdaBucket:
    Type: String
    Default: 'cf-templates-iio8e9bj1plf0-us-west-2'
    Description: 'S3 bucket containing the Lambda deployment package'
  
  LambdaZipFile:
    Type: String
    Default: 'text_processor.zip'
    Description: 'Name of the Lambda deployment package ZIP file'

Resources:
  NepaliTranslatorLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SSMAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ssm:GetParameter'
                Resource: 
                  - 'arn:aws:ssm:us-west-2:874956223356:parameter/HUGGINGFACE_KEY'

  NepaliTranslatorLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: NepaliTranslator
      Handler: lambda_function.lambda_handler
      Role: !GetAtt NepaliTranslatorLambdaRole.Arn
      Code:
        S3Bucket: !Ref LambdaBucket
        S3Key: !Ref LambdaZipFile
      Runtime: python3.9
      Timeout: 45
      MemorySize: 256

  NepaliTranslatorFunctionUrl:
    Type: 'AWS::Lambda::Url'
    Properties:
      AuthType: NONE
      TargetFunctionArn: !Ref NepaliTranslatorLambda
      Cors:
        AllowCredentials: false
        AllowHeaders:
          - 'Content-Type'
        AllowMethods:
          - 'POST'
          - 'OPTIONS'
        AllowOrigins:
          - '*'
        MaxAge: 300

Outputs:
  LambdaFunctionUrl:
    Description: 'URL for the Lambda function'
    Value: !GetAtt NepaliTranslatorFunctionUrl.FunctionUrl